### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by zhangzhishan** [ashfinal/awesome-hammerspoon#1]
并不懂lua，所以问一下，报错内容如下：
```
*** ERROR: /Users//.hammerspoon/init.lua:42: attempt to concatenate a nil value
stack traceback:
	/Users//.hammerspoon/init.lua:42: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
	(...tail calls...)
```
第42行内容为：
```
 privatepath = hs.fs.pathToAbsolute(hs.fs.currentDir()..'/private')
```

**Comment by ashfinal** [comment]
有可能是 hammerspoon 权限不够造成的，可以尝试安装完 hammerspoon 后开启辅助控制选项。

**Comment by zhangzhishan** [comment]
已经开启了

-- 祝您工作顺利，身体健康 张治山 18392383167 zhangzhishanlo@gmail.com
On Wed, Nov 30, 2016 at 10:43 PM, ashfinal <notifications@github.com> wrote:
有可能是 hammerspoon 权限不够造成的，可以尝试安装完 hammerspoon 后开启辅助控制选项。

**Comment by zhangzhishan** [comment]
好像装了最新版就可以了，之前用cask安装的

-- 祝您工作顺利，身体健康 张治山 18392383167 zhangzhishanlo@gmail.com
On Wed, Nov 30, 2016 at 10:45 PM, 张治山 <zhangzhishanlo@gmail.com> wrote:
已经开启了

-- 祝您工作顺利，身体健康 张治山 18392383167 zhangzhishanlo@gmail.com
On Wed, Nov 30, 2016 at 10:43 PM, ashfinal <notifications@github.com> wrote:
有可能是 hammerspoon 权限不够造成的，可以尝试安装完 hammerspoon 后开启辅助控制选项。

**Comment by laxapple** [comment]
因为 hs.fs.pathToAbsolute() 这个方法是 0.9.49 版本新增的

**Comment by ashfinal** [comment]
@laxapple 用的最新版，这问题还真挺难发现的
