### ISSUE TITLE
In RESIZE mode ⌘ + hjkl will go through windows back and forth but not cycle through them, could it be added?

### ISSUE THREAD

**Issue by nikivdev** [ashfinal/awesome-hammerspoon#10]
What I mean is that if I press cmd + l in RESIZE mode, it will switch between active windows, but when you reach the 'end', it will just stop and not cycle through them. It would be really useful I think to give an option to actually cycle through windows so I have two active windows, pressing cmd + l repeatedly, will go back and forth between them without stop.

Also cmd + j/k do nothing for me. What are they supposed to do? :)

**Comment by ashfinal** [comment]
This is Hammerspoon API 's default behavior.

Yeah, I also found it is a little wired. I've tried to solve this problem on last some commit, (and nearly found something to make it work), but I'm interrupt by something else.

I'll find time to repick it up in the near future, and use just one hotkey (CMD + L) to cycle through all windows.

**Comment by ashfinal** [comment]
Now use only `CMD+H/L` to cycle throuth all windows in `RESIZE` mode. https://github.com/ashfinal/awesome-hammerspoon/commit/fb2748beace1e6d7f97868f0ecbb99101e5ae8de

I hope this solves your problem.

**Comment by nikivdev** [comment]
Thank you, this is perfect. :)
