### ISSUE TITLE
Help with rebinding of one of the actions in basic mode

### ISSUE THREAD

**Issue by nikivdev** [ashfinal/awesome-hammerspoon#11]
I wanted to rewrite one of the actions in basic mode to instead of scrolling, call a certain hotkey. (option and arrows to be exact).

I tried rewriting it as follows : 

```
viewM:bind('', 'H', 'Scroll Leftward', function() hs.eventtap.keyStroke("option", "left") end)
viewM:bind('', 'L', 'Scroll Rightward', function() hs.eventtap.keyStroke("option", "right") end)
viewM:bind('', 'J', 'Scroll Downward', function() hs.eventtap.keyStroke("option", "down") end)
viewM:bind('', 'K', 'Scroll Upward', function() hs.eventtap.keyStroke("option", "up") end)
```
I would think that it would make hjkl, call the hotkeys in VIEW mode, but it didn't work. Do you perhaps know what might cause this issue?

Thank you for any help.

**Comment by ashfinal** [comment]
Use `alt` instead of `option`.
You can read the manual more carefully. :)
http://www.hammerspoon.org/docs/hs.eventtap.html

**Comment by nikivdev** [comment]
That too doesn't work for me. :(

```XML
viewM:bind('', 'H', 'Scroll Leftward', function() hs.eventtap.keyStroke({"alt"}, "left") end)
viewM:bind('', 'L', 'Scroll Rightward', function() hs.eventtap.keyStroke({"alt"}, "right") end)
viewM:bind('', 'J', 'Scroll Downward', function() hs.eventtap.keyStroke({"alt"}, "down") end)
viewM:bind('', 'K', 'Scroll Upward', function() hs.eventtap.keyStroke({"alt"}, "up") end)
```

**Comment by nikivdev** [comment]
Also if you want to know, what I am trying to do, I am replacing Hammerspoon scrolling to Karabiner's. (can be found [here](https://github.com/tekezo/Files/blob/master/Karabiner/private.mouse_keys_mode_v2_option/private.xml))

It is a lot more smooth this way.

**Comment by ashfinal** [comment]
This works for me.
Just open Hammerspoon console, paste the above code and try again.

I'm thinking you may have put these code into `awesomeconfig.lua`? That will not work.
They are "shadowed". You need **replace** the corresponding lines with the code above.

**Comment by ashfinal** [comment]
And I don't see it makes more smooth.
If scrolling one line one time is too short for you, you can scroll faster, which may act more smooth.
```
viewM:bind('', 'J', 'Scroll Downward', function() hs.eventtap.scrollWheel({0,-1},{},"line") end, nil, function() hs.eventtap.scrollWheel({0,-1},{},"line") end)
```
Change `-1` to `-2` (or `-3/4…`) to scroll faster.

**Comment by nikivdev** [comment]
You are right that it is smooth enough if you adjust the settings well enough.

Still though, my binds for sending a keystroke don't work at all (In this case I want when M pressed to switch application) : 

```Lua
viewM:bind('', 'escape', function() viewM:exit() end)
viewM:bind('', 'Q', function() viewM:exit() end)
viewM:bind('', 'tab', function() showavailableHotkey() end)

viewM:bind('', 'H', 'scroll leftward', function() hs.eventtap.scrollWheel({1,0},{},"line") end, nil, function() hs.eventtap.scrollWheel({1,0},{},"line") end)
viewM:bind('', 'J', 'scroll downward', function() hs.eventtap.scrollWheel({0,-1},{},"line") end, nil, function() hs.eventtap.scrollWheel({0,-1},{},"line") end)
viewM:bind('', 'K', 'scroll upward', function() hs.eventtap.scrollWheel({0,1},{},"line") end, nil, function() hs.eventtap.scrollWheel({0,1},{},"line") end)

viewM:bind('', 'L', 'scroll rightward', function() hs.eventtap.scrollWheel({-1,0},{},"line") end, nil, function() hs.eventtap.scrollWheel({-1,0},{},"line") end)

viewM:bind('', 'M', 'switch app', function() hs.eventtap.keyStroke({"cmd"}, "tab") end)


viewM:bind('shift', 'H', 'scroll leftward', function() hs.eventtap.scrollWheel({3,0},{},"line") end, nil, function() hs.eventtap.scrollWheel({3,0},{},"line") end)
viewM:bind('shift', 'J', 'scroll downward', function() hs.eventtap.scrollWheel({0,-3},{},"line") end, nil, function() hs.eventtap.scrollWheel({0,-3},{},"line") end)
viewM:bind('shift', 'K', 'scroll upward', function() hs.eventtap.scrollWheel({0,3},{},"line") end, nil, function() hs.eventtap.scrollWheel({0,3},{},"line") end)

viewM:bind('shift', 'L', 'scroll rightward', function() hs.eventtap.scrollWheel({-3,0},{},"line") end, nil, function() hs.eventtap.scrollWheel({-3,0},{},"line") end)
```

I am changing and editing the basic mode.lua file directly, not editing anything in awesomeconfig.lua.

**Comment by nikivdev** [comment]
Also tried to add 'M' key as a way to quit from the mode : 

```Lua
viewM:bind('', 'escape', function() viewM:exit() end)
viewM:bind('', 'Q', function() viewM:exit() end)
viewM:bind('', 'M', function() viewM:exit() end)
```

I would think that binding M key in this way would work but it doesn't for some reason. Nothing happens as I press it in this viewM mode.

**Comment by ashfinal** [comment]
Hum … That is strange. Switching application and exiting `VIEW` mode, both work for me here.
Maybe you forgot to reload configuation? Or modify some code else? 

Open Hammerspoon console, paste the code below, then try pressing `j` again.
``` lua
tmp = hs.hotkey.bind("","j",nil,function() hs.eventtap.keyStroke({"cmd"},"tab") end)
```
`tmp:delete()` to cancel this temporary hotkey binding/test.
