### ISSUE TITLE
How can I isolate windows hint functionality to just one function?

### ISSUE THREAD

**Issue by nikivdev** [ashfinal/awesome-hammerspoon#12]
I really love this feature : 

![2017-01-05 at 00 01](https://cloud.githubusercontent.com/assets/6391776/21662473/195f5e34-d2da-11e6-81cf-03056e424f5a.png)

I wish I can call it externally with url scheme and I wanted to move the modal switching from hammer spoon to karabiner. I can't however figure out what to do, to implement the win hints functionality. Ideally I want to make it into a function like [this one](https://github.com/nikitavoloboev/dotfiles/blob/master/hammerspoon/init.lua#L140). 

I've looked through the source code and still can't figure it out. It seems to be heavily linked to modal switching.

Thank you for any help.

**Comment by ashfinal** [comment]
I've never used karabiner. 
But from [this tutorial](http://www.hammerspoon.org/go/#karabinerurl), I think the functionality can be 
implemented. The example in tutorial is quite similar to yours.

**Comment by nikivdev** [comment]
Oh no, you misunderstood me. I know how to call lua functions from Karabiner. What I don't know, is what to call to get the winhints show up. I don't get where it is defined so I can move it to just my init.lua to call from. :)

**Comment by ashfinal** [comment]
I just saw your `init.lua` file. 
Do you mean that you can call all lua functions from Karabiner, except "showWindowHints" function?
If so, that doesn't make sense. Showing windows hint did not link to modal switching, and was not defined anywhere else. It belongs to Hammerspoon's original functions.

I just test the code below in Hammerspoon console with your `init.lua` file, and it works as intended.
``` lua
hs.urlevent.openURLWithBundle("hammerspoon://showWindowHints","com.apple.Safari")
```
So I presume you may do something wrong on Karabiner's side. Wish that helps. :)

**Comment by nikivdev** [comment]
Well I am only calling `hs.hints.windowHints()` but that is not enough it seems.

Do you use something to draw the icons that show up and the lettering here : 

![](http://i.imgur.com/4Gr2ezl.png)

**Comment by ashfinal** [comment]
No, I didn't do anything else. http://www.hammerspoon.org/docs/hs.hints.html
You can see something in Hammerspoon console which can help to identify the problem?

**Comment by nikivdev** [comment]
Hey @ashfinal, I think I got it working now. :D

One thing though is that for some reason it doesn't display window names when there are many windows open : 

![2017-01-07 at 20 01](https://cloud.githubusercontent.com/assets/6391776/21744353/1d2521d4-d514-11e6-9ade-8ac862df8377.png)

**Comment by nikivdev** [comment]
Did you add anything to `   hs.hints.windowHints()` to get around this?

**Comment by ashfinal** [comment]
@nikitavoloboev By default window hints will show their titles if there are less than 4 windows on screen.
`hs.hints.showTitleThresh = 0` 
Change `0` to some number larger than 4, this should do the work.

**Comment by nikivdev** [comment]
Thank you a lot @ashfinal, this worked
