### ISSUE TITLE
How to modify the "mode status window"?

### ISSUE THREAD

**Issue by MagisDing** [ashfinal/awesome-hammerspoon#13]
Please forgive for my ignorance, but how to change the default appearance and location of the "mode status window"( which I am referring the black block that indicates the current mode，shows “dock mode" by default) sits in the right downside corner of the screen? I wish it could be auto-hidden, it would be grateful if you show me how to achieve it, thx.

您好，打扰。请问屏幕右下角modal切换状态显示框如何修改其属性（比如大小，半透明程度，位置）？能否设置其自动隐藏，只有激活时显示？

**Comment by ashfinal** [comment]
To set mode block to be auto-hidden, see the manual's `Customization`'s `Global options`.
Create the file `~/.hammerspoon/private/awesomeconfig.lua` and put the line below into it:
``` lua
idle_to_which = "hide"
```

To set it's default appearance and location, well ... unfortunately at present there are no those options provided.  But they can be done if you're brave enough to get your hands dirty :)
There are two global objects you can access: `modal_bg` and `modal_show`, which represent mode block's background and text respectively.
Open your hammerspoon console, input this:
``` lua
modal_bg:setFrame(hs.geometry.rect(0,0,170,19))
modal_bg:setAlpha(0.5)
```
The disadvantage is these settings are not persisted.

**Comment by MagisDing** [comment]
@ashfinal Thx for your reply. I've added 
`idle_to_which = "hide"`
to the file, but it only works after reloading config every time, which is quite weird.

**Comment by ashfinal** [comment]
Last night I'm so idiot to force push, losing some commits. :(
I'm trying to restore them now. Keep clam and wait for some time.
It should be available by tomorrow morning.
Sorry for the inconvenience.

**Comment by ashfinal** [comment]
Sorry, got something else to do.
The commit history has been restored, and `idle_to_which` option should works now.
Thanks for your patience. :)
