### ISSUE TITLE
It would be nice to have a method to move a window to another screen

### ISSUE THREAD

**Issue by Michael-Jing** [ashfinal/awesome-hammerspoon#16]
Currently I can move window to the left or right half of the screen, but it stops with only one screen, when external monitor is used, there is no easy way to move window to another screen/monitor.

**Comment by ashfinal** [comment]
This can be done according to Hammerspoon's docs. But I don't have external monitor to test this.
I will add this feature ASAP.

**Comment by ashfinal** [comment]
Thank to @cleme1mp's work, now you can move windows to another screen.

If it works fine for you, I'm closing this issue.

**Comment by Michael-Jing** [comment]
Yes, please go ahead.
