### ISSUE TITLE
外接显示器widget和dock model位置不对！

### ISSUE THREAD

**Issue by swieer** [ashfinal/awesome-hammerspoon#22]
widget其它人有提这个问题我就不多说了。
我外接27寸2560*1440的显示器，Dock model显示网速的提示出现在了屏幕的中央，请问哪里可能改，或者大神给一个更新。谢谢！

**Comment by ashfinal** [comment]
27寸显示器是唯一的屏幕吗？
可以先试着刷新下配置（快捷键 cmd+ctrl+shift+R），如果还是显示不正常，可能是分辨率没能正常识别。这种情况下你可能需要向 Hammerspoon 上游反馈。
Mode Block 定义是在 init.lua 文件 106 行[init.lua](https://github.com/ashfinal/awesome-hammerspoon/blob/master/init.lua#L106)，相关的文档在[这里](http://www.hammerspoon.org/docs/hs.screen.html)。
