### ISSUE TITLE
Some window movement commands cause windows to be relocated to another monitor

### ISSUE THREAD

**Issue by cro** [ashfinal/awesome-hammerspoon#27]
A common workflow for me is to throw a window to another monitor and then size it to half the screen.  With my previous hammerspoon config this worked fine, but I've noticed that since I've started using this config the window will often revert back to the previous monitor.  I can workaround this by sizing to half the screen first, and then throwing to the next monitor, but this only works when the window is on the left half.

**Comment by ashfinal** [comment]
Current config doesn't work well on multi-monitors because I'm lack of relevant hardware.
But today I've got some kind of second monitor, and I'm trying to make improvements under multi-monitors's condition. 
This may make a while, be patient please. Sorry for the inconvenience. :)

**Comment by cro** [comment]
No worries, thank you for putting this on Github. If I have time in the next few days I will try to put together a PR. I have 3 monitors including my laptop display (they are older, smaller ones) so I might be able to give that support a good workout.

**Comment by ashfinal** [comment]
Thank you very much! ❤️

Today I've made some improments, new commits should make this config work well on multi-monitors now. If I break something, please file an issue. :)
