### ISSUE TITLE
希望可以添加一个一年过去了百分比的widget

### ISSUE THREAD

**Issue by zhangzhishan** [ashfinal/awesome-hammerspoon#28]
希望可以添加一个一年过去了百分比的widget。

**Comment by ashfinal** [comment]
倒是挺好实现，也有这个需求。
只是目前手头还有其它东西要写：https://github.com/ashfinal/awesome-hammerspoon/projects/2
这个恐怕得往后推一推。

可以尝试自己实现一下。新开个文件用 hs.drawing 或者 hs.canvas 直接写（画），整完就算完成一个“模块”了，然后在 init.lua 文件里 require 一下就行。

**Comment by ashfinal** [comment]
比想象中要麻烦一点，不过还是画了个感觉不错的。https://github.com/ashfinal/awesome-hammerspoon/commit/d3cb8471e158bbb441a464fadcec503fc74dc232
![timelapsed](https://github.com/ashfinal/bindata/raw/master/screenshots/awesome-hammerspoon-elapsed.png)
