### ISSUE TITLE
希望可以考虑把部分配置文件改成本地配置的

### ISSUE THREAD

**Issue by zhangzhishan** [ashfinal/awesome-hammerspoon#3]
快捷键本地修改后，每次git pull 都会覆盖，还需要重新修改，不知道有什么好的解决办法没有

**Comment by ashfinal** [comment]
确实有这方面需求。
但现在快捷键太多，为每一个都提供自定义选项有点不太现实。
我目前能想到的是 opt+space、opt+tab 这俩组合键容易和其它软件冲突

能说下你都修改了哪些默认按键嘛？方便我把这些键做成可以配置的。
这样就能统一在 `~/.hammerspoon/private/awesomeconfig.lua` 文件里自定义了。

**Comment by zhangzhishan** [comment]
主要是模式切换方面的，一直在用manico默认的是option键切换应用，还有就是option+space是alfred的快捷键，所以冲突的还是挺多的。

-- 祝您工作顺利，身体健康 张治山 18392383167 zhangzhishanlo@gmail.com
On Thu, Dec 8, 2016 at 10:28 AM, ashfinal <notifications@github.com> wrote:
确实有这方面需求。
但现在快捷键太多，为每一个都提供自定义选项有点不太现实。
我目前能想到的是 opt+space、opt+tab 这俩组合键容易和其它软件冲突

能说下你都修改了哪些默认按键嘛？方便我把这些键做成可以配置的。
这样就能统一在 ~/.hammerspoon/private/awesomeconfig.lua 文件里自定义了。

**Comment by ashfinal** [comment]
option+space 我感觉应该提供个配置选项。
至于 manico 其实可以考虑替换掉，固定的app用`app mode`，不固定的用`opt+tab` windows hint。

当然以上两个软件我都没用过，只是个随便建议。

目前 Hammerspoon 与 option 相关的配置全部在 `modalmgr.lua` 文件里，总共才60行。
不行就把这个文件也做成可以插拔的，就可以单独放到 `private` 文件夹了。

**Comment by zhangzhishan** [comment]
嗯 我也重新配置了一些app mode里面的配置，不过manico胜在只需要一次按键就可以调出相关应用吧。

-- 祝您工作顺利，身体健康 张治山 18392383167 zhangzhishanlo@gmail.com
On Thu, Dec 8, 2016 at 11:09 AM, ashfinal <notifications@github.com> wrote:
option+space 我感觉应该提供个配置选项。
至于 manico 其实可以考虑替换掉，固定的app用 app mode ，不固定的用 opt+tab windows hint。

当然以上两个软件我都没用过，只是个随便建议。

目前 Hammerspoon 与 option 相关的配置全部在 modalmgr.lua 文件里，总共才60行。
不行就把这个文件也做成可以插拔的，就可以单独放到 private 文件夹了。

**Comment by ashfinal** [comment]
好吧，app mode 多了一次按键。。。anyway 这个是个人喜好问题，不讨论这个。

下午我就把这方面重新思考改动下，让配置更灵活，更容易上手些。

**Comment by clotong** [comment]
举个例子，我把Caps Lock绑定了"cmd", "alt", "ctrl"，然后Caps+I定义了一个快捷键，但是配置里面alt + I是Timer Mode，当我按下Caps+I，貌似两者会冲突，会先启动Timer Mode，再按一次才能启动我Caps+I定义的快捷键，能解决这个问题嘛

**Comment by ashfinal** [comment]
@clotong `cmd+alt+ctrl+I` 确实绑定了 Timer Mode，除此之外还有类似的。
当时觉得这些按键这么长，不会有人用到，做个备用总是好的。
现在看来其实并没有起到作用，反而带来一些困惑和麻烦。

考虑在下次更新中全部删掉，把主动权交给用户。

**Comment by ashfinal** [comment]
抱歉各位，拖了这么长时间。
刚刚提交了一个版本，现在绝大部分的默认绑定键均可自定义，应该不会遇到以上所说的问题了。

自定义方法：`hsreload_keys = {{"cmd", "shift", "ctrl"}, "F”}` 

全部可用的变量名称请查阅 `Customization` 的第三部分。
同时修复了两三处已知的小问题，推荐更新。
