### ISSUE TITLE
Initial working directory

### ISSUE THREAD

**Issue by nathancraig** [ashfinal/awesome-hammerspoon#32]
After installing and reloading the configuration, I received an error that hs.fs.currentDir returned nil (line 23 of init). Fixed by adding hs.fs.chdir('~/.hammerspoon') before the currentDir call.

**Comment by ashfinal** [comment]
New commit: [a7bdb4f](https://github.com/ashfinal/awesome-hammerspoon/commit/a7bdb4fd2601e5680a780a070750364d3e20f314)
