### ISSUE TITLE
当使用系统的 Spotlight 时行为不正常

### ISSUE THREAD

**Issue by bao3** [ashfinal/awesome-hammerspoon#33]
系统搜索的列表会不断被刷新，因此不能往下翻动。解决办法就是退出 hammerspoon。
希望可以解决一下。

**Comment by ashfinal** [comment]
可以描述的更清楚一点。
意思是当 Spotlight 激活时，它的列表会自动不停的刷新，导致不能向下滚动？
只要 hammerspoon 运行着就有这种问题？加载配置后有没有做别的操作？

最好能给出在我电脑上重现的步骤。

**Comment by ashfinal** [comment]
因无法重现关闭该 issue ，视情况日后开启。
