### ISSUE TITLE
Only the window management

### ISSUE THREAD

**Issue by scottming** [ashfinal/awesome-hammerspoon#38]
I like this hammerspoon config, it's awesome, but I just want the part of window management, how can I get it?

**Comment by ashfinal** [comment]
See [customization](https://github.com/ashfinal/awesome-hammerspoon#customization) section.

Create `~/.hammerspoon/private/awesomeconfig.lua` file, add those lines:

``` lua
 module_list = {
     "modes/basicmode",
 }
```

Reload your config, then you should get what you wanted.

**Comment by scottming** [comment]
Thanks, I got it.
If I want to hide the shortcut list image or make it transparent, which code should I modify? I think it blocked my sight.

![](http://7xjuve.com1.z0.glb.clouddn.com/170704-hammerspoon_shortcut_list.jpeg)

**Comment by ashfinal** [comment]
Add a line into `~/.hammerspoon/private/awesomeconfig.lua` :

``` lua
show_resize_tips = false
```
