### ISSUE TITLE
多显示器Widget显示错误

### ISSUE THREAD

**Issue by anxsec** [ashfinal/awesome-hammerspoon#4]
多显示器并且将外接显示器(分辨率高于内置显示器)设置为主显示器时widget按照原来的分辨率绘制

**Comment by ashfinal** [comment]
目前 widgets 没有针对多种分辨率进行适配，主要原因是没有硬件条件来做。
有条件的话，修改起来应该非常简单（代码行数均为100行左右）。
希望可以自己动手，可以的话推上来造福大家。

文件名分别为 `~/.hammerspoon/widgets/analogclock.lua` , `~/.hammerspoon/widgets/calendar.lua`

**Comment by anxsec** [comment]
@ashfinal 最近要考试了没时间折腾lua，考完如果没有其他好心人解决的话我再看看
