### ISSUE TITLE
Unable to load image: ./resources/watchbg.png stack traceback

### ISSUE THREAD

**Issue by katongzhong1** [ashfinal/awesome-hammerspoon#40]
*** ERROR: ...on.app/Contents/Resources/extensions/hs/drawing/init.lua:88: Unable to load image: ./resources/watchbg.png
stack traceback:
	[C]: in function 'hs.image.imageFromPath'
	...on.app/Contents/Resources/extensions/hs/drawing/init.lua:88: in function 'hs.drawing.internal.image'
	/Users/wushengzhong/.hammerspoon/widgets/analogclock.lua:16: in function 'showAnalogClock'
	/Users/wushengzhong/.hammerspoon/widgets/analogclock.lua:146: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:529: in function 'require'
	/Users/wushengzhong/.hammerspoon/init.lua:372: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:561: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by ashfinal** [comment]
Sorry for the late reply. 
Did you install Hammerspoon with Homebrew?
I guess this may change its working directory, which results in this error.
I'll test more at tomorrow and push a update for this.

**Comment by ashfinal** [comment]
I believe this issue has been solved.
Please pull the lastest commit, and reload the configuration.
