### ISSUE TITLE
new wallpaper source

### ISSUE THREAD

**Issue by ultimate010** [ashfinal/awesome-hammerspoon#42]
Hi, this repo is so useful, Thanks. But I found that use bingdaily picture as wallpaper too boring, so I add a new module that use [unsplash](https://unsplash.com/) as source, can I make a pull requests?

**Comment by ashfinal** [comment]
Surely you can. 
Create a new file (module) similar to `bingdaily.lua`, say `unsplashwp.lua` in `~/.hammerspoon/misc`.
Then make a pull request.

Since we can choose to load which modules in `~/.hammerspoon/private/awesomeconfig.lua` file. Your module could benefit lots of people. :)

**Comment by ultimate010** [comment]
Thanks.
