### ISSUE TITLE
当我关闭 shortcut 显示后，窗口模式下，如何让那个红点居中呢？

### ISSUE THREAD

**Issue by scottming** [ashfinal/awesome-hammerspoon#43]
如题，用的是大屏，所以希望防止误按。

**Comment by ashfinal** [comment]
养成操作后随手按 `q` 或者 `esc` 的习惯。
没有红点居中选项，可以自己 fork 一份，改下 init.lua 文件里的红点坐标。

**Comment by scottming** [comment]
请问下，具体是在哪个位置呢？不熟悉 Lua😂

**Comment by ashfinal** [comment]
https://github.com/ashfinal/awesome-hammerspoon/blob/master/init.lua#L136

**Comment by scottming** [comment]
请问下新版的该在哪里修改了呢？

https://github.com/ashfinal/awesome-hammerspoon/blob/master/Spoons/ModalMgr.spoon/init.lua#L29 这个地方修改是无效的。

```lua
 modal_tray = hs.canvas.new(mainScreen:localToAbsolute({x=300,y=600,w=20,h=20}))
```

**Comment by scottming** [comment]
另外，我 git pull 最新版之后，shift + h/j/k/l 都无法移动了。变成了伸展，很不习惯。请问现在移动的快键键是啥？

**Comment by ashfinal** [comment]
modal_tray 坐标在这里定义：https://github.com/ashfinal/awesome-hammerspoon/blob/2f656505020ce83801bdf3719adc00d8a37b016f/Spoons/ModalMgr.spoon/init.lua#L148

最新版改成用 `a/w/s/d` 移动了。按 `tab` 键可以切换 help panel。

**Comment by scottming** [comment]
已经搞定了，非常感谢。最新版的整体架构合理了好多，看着很清爽。
另外 help panel 里面的上下左右，有什么用？切换的 focus app 么？为何按了之后没效果呢？

**Comment by ashfinal** [comment]
> 另外 help panel 里面的上下左右，有什么用？

多屏显示器用的。比如说你连接了两台显示器，就可以一键把当前窗口移到另一台显示器。

如果只有一台显示器，是不起作用的。
