### ISSUE TITLE
Add a shortcut to show/hide all widgets

### ISSUE THREAD

**Issue by joshua7v** [ashfinal/awesome-hammerspoon#45]
Hey. Love your config.

Desktop widgets never have a chance to show since there are always some windows on top of them.
So, I think to add a shortcut to show/hide all widgets on the top level should make sense.

what do you think of it?

![screen shot 2017-07-24 at 2 19 03 pm](https://user-images.githubusercontent.com/4159858/28510521-7eddf196-707b-11e7-80dc-ae00eeca56c7.png)

**Comment by ashfinal** [comment]
Showing/hiding a widget is good, but all widgets is too much. 
And also there may be more widgets coming, which makes the thing complicated.

I suggest you add some lines in `~/.hammerspoon/private/awesomeconfig.lua` to do what you want.
Thus, you can continue to benefit from this repo, meanwhile by pressing a shortcut bring up the widgets to the front, as you intended to.

If you need some help, feel free to let me know. :)

**Comment by ashfinal** [comment]
For now, `timelapsed` widget can be easily brought up by calling `timelapsed_canvas:bringToFront()`, sent to back by `timelapsed_canvas:sendToBack()`.
But the early created widgets, i.e. `calendar`, `analogclock`, `hcalendar`, are not easy to do so. Because they consist of some parts of `hs.drawing` . 
I'm planing to refactor these widgets with `hs.canvas`, the work will be done at tomorrow morning at the latest, I suggest you hold on before then.

**Comment by joshua7v** [comment]
@ashfinal thanks, actually i've already tried. 
The screenshot shows my work. Code is on the right half.
I don't think I am the only one who need this feature.
So I think maybe you will have an interest in supporting it officially.(maybe in a different way)

**Comment by ashfinal** [comment]
Aha, I didn't notice your code. Glad you worked it out. :)
Still, I'll rewrite these widgets with `hs.canvas`. I'm encounting some problem, but I will finish the work eventually. We can expect the code to be clean, extensible, and most important, respond to user interaction.

I'll leave this issue open until I make some progress.

**Comment by ashfinal** [comment]
Sorry for the delay. The work is done, eventually.
Now you can use the code below to toggle its visibility.
``` lua
function toggleVisibility()
    if not calendarCanvas:isVisible() then calendarCanvas:bringToFront() else calendarCanvas:sendToBack() end
end
```
`analogclockCanvas`, `hcalendarCanvas`, `timelapsed_canvas`… can also be called like that.
