### ISSUE TITLE
Unable to disable window hints

### ISSUE THREAD

**Issue by thisgeek** [ashfinal/awesome-hammerspoon#46]
Previously, I was able to disable window hints with this line in my custom configuration:

```
winhints_keys = {{}, ""}
```

I tried updating this for the new variable name:

```
hswhints_keys = {{}, ""}
```

but this will produce the following error when I reload:

```
*** ERROR: ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:432: Invalid key:  - this may mean that the key requested does not exist in your keymap (particularly if you switch keyboard layouts frequently)
stack traceback:
	[C]: in function 'error'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:23: in upvalue 'getKeycode'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:192: in function 'hs.hotkey.new'
	...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:432: in method 'bind'
	/User/me/.hammerspoon/init.lua:49: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:561: in function 'hs._coresetup.setup'
	(...tail calls...)
```

For now I work around it by commenting out the "Register windowHints" code. It would be nicer if there were a way to simply disable it.

**Comment by ashfinal** [comment]
[This commit](https://github.com/ashfinal/awesome-hammerspoon/commit/b1abb1934e5a831dda1d3731aa2c8e53599694d4) should get your problem solved. 
Just `git pull` and reload the configuration.

And, Thanks for your feedback! ❤️
