### ISSUE TITLE
Calendar date is not correct

### ISSUE THREAD

**Issue by joshua7v** [ashfinal/awesome-hammerspoon#47]
![image](https://user-images.githubusercontent.com/4159858/29952908-f06c98f2-8efe-11e7-8c16-103abd7bdb83.png)

**Comment by ashfinal** [comment]
Thanks for your feedback.
It turns out HCalendar's canvas wasn't trimmed properly. I've fixed it in [56f2f51](https://github.com/ashfinal/awesome-hammerspoon/commit/56f2f5191bc983eeb8db1b5c60b3041814e08f3d), please run `cd ~/.hammerspoon && git pull`, then reload the configuration.
