### ISSUE TITLE
how to open Terminal?

### ISSUE THREAD

**Issue by sallenhandong** [ashfinal/awesome-hammerspoon#57]
opention + t no response,what should i do?

**Comment by esaruoho** [comment]
@sallenhandong i'm not sure why something like this wouldn't work for you?

```
  hs.hotkey.bindSpec({ { "shift", "cmd", "alt"}, "T" },
    function()
      hs.application.launchOrFocus("Terminal")
    end
  )  
```

or are you specifically talking about something else with your `opention +t`  ?
