### ISSUE TITLE
[feature request] allow to change to and from one mode from same hotkey

### ISSUE THREAD

**Issue by nikivdev** [ashfinal/awesome-hammerspoon#7]
So for example I can trigger window management with ⌥ + R and then cancel the mode to go to DOCK mode with pressing escape.

I wish you could trigger window management with same hotkey, but if already in window management mode, it would go back to DOCK mode. I wish it would apply to any other mode out there too. This would be extremely useful for me as I like to quickly jump into one mode and then go back and I don't want to press escape for it. This doesn't mean you should remove the ability to press escape to return to default mode, just give an option to trigger into / from one mode with same hotkey.

**Comment by ashfinal** [comment]
There is a time when you can use the same hotkey (and `Escape`, and `q`) to cancel the mode to go to DOCK mode. Totally three hotkeys. 

Then during some code-cleanup, I felt there may be too many. So I just simply delete them all, leaving only `Escape` and `q`.

If you found urgent to have this option, yes, it can be added back. :)

**Comment by nikivdev** [comment]
Oh I see, this makes sense. :)

While not urgent, I think it would be nice to have the option of making the mode switching key a little bit more useful. I think it only adds to the experience.

**Comment by ashfinal** [comment]
I found `Escape` and `q` is good enough for me. :)
Still, adding an option (default on/off) for this may make the repo suit to more people.
But, this will not be on the urgent list.

**Comment by nikivdev** [comment]
Yes, of course. Both escape and q work great indeed. :)
