### ISSUE TITLE
How to make it so that DOCK MODE and network monitoring does not show at all, only modes show

### ISSUE THREAD

**Issue by nikivdev** [ashfinal/awesome-hammerspoon#8]
I find always seeing the network monitoring really distracting. So as seeing DOCK MODE.

What I think would be great, is to always hide it by default, and only show users what mode they are in that is not the default. So if I was in resize window mode, it would show me this permanently until I quit the mode : 

![2016-12-31 at 16 01](https://cloud.githubusercontent.com/assets/6391776/21578058/725abe5e-cf72-11e6-8c1b-25b3a13e1365.png)

When in view mode, show this : 

![2016-12-31 at 16 02](https://cloud.githubusercontent.com/assets/6391776/21578060/8b72c5da-cf72-11e6-9338-d0a34b03cab5.png)

And so on. Absence of the mode bar, indicates that I am in normal mode. This would be really amazing to have to complete this superb hammer spoon framework. Thank you for this.

I hope this would be possible to change.

**Comment by ashfinal** [comment]
Just put the line below into `~/.hammerspoon/private/awesomeconfig.lua` and reload configure.

`idle_to_which = “hide"`

Then see if it works as intended.

You are welcome. : )

**Comment by nikivdev** [comment]
I tried adding the line to my awesomeconfig.lua file but I get this error : 

![2017-01-01 at 13 34](https://cloud.githubusercontent.com/assets/6391776/21581200/2fe37042-d027-11e6-9741-1d862a0e1df0.png)

And here it is in text : 

```
2017-01-01 13:36:04: -- Lazy extension loading enabled
2017-01-01 13:36:04: -- Loading ~/.hammerspoon/init.lua
2017-01-01 13:36:04: -- Loading extension: hotkey
2017-01-01 13:36:04: 13:36:04     hotkey: Enabled hotkey ⌘⌃⌥I
2017-01-01 13:36:04:              hotkey: Enabled hotkey ⌘⌃⌥K
2017-01-01 13:36:04:              hotkey: Enabled hotkey ⌘⇧F12
2017-01-01 13:36:04: -- Loading extension: wifi
2017-01-01 13:36:04:              hotkey: Enabled hotkey ⌘⌃⌥W
2017-01-01 13:36:04: -- Loading extension: window
2017-01-01 13:36:04: -- Loading extension: uielement
2017-01-01 13:36:04: -- Loading extension: urlevent
2017-01-01 13:36:04: -- Loading extension: drawing
2017-01-01 13:36:04: -- Loading extension: fs
2017-01-01 13:36:04: *** ERROR: error loading module 'private/awesomeconfig' from file '/Users/nikivi/.hammerspoon/private/awesomeconfig.lua':
	/Users/nikivi/.hammerspoon/private/awesomeconfig.lua:13: unexpected symbol near '<\226>'
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:449: in function 'require'
	/Users/nikivi/.hammerspoon/init.lua:125: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
	(...tail calls...)
```

I tried it both on empty awesomeconfig.lua file and adding it as separate line. Both threw the error at me. This is all I have in my awesomeconfig file : 

![2017-01-01 at 13 39](https://cloud.githubusercontent.com/assets/6391776/21581213/d7ad500e-d027-11e6-961c-7869d592bd10.png)

**Comment by ashfinal** [comment]
My bad. 😓 I forget to toggle input method before typing.

`idle_to_which = "hide"` or
`idle_to_which = 'hide'` 

Both are ok. It should be "English" doube-quote symbol.

**Comment by nikivdev** [comment]
Thank you. Is it possible to lower the time it goes to idle mode to 1 or 2 seconds when switching from other modes. So it just flashes briefly and then hides away.

**Comment by ashfinal** [comment]
Sorry, for now there is not this option.

But if it's very important to you, and you can read some code, and you don't care interrupting the update procedure.

Change the 12th line of `~/.hammerspoon/modalmgr.lua`:

`idletimer = hs.timer.doEvery(5,check_idle)`

Change 5 to the number you want.

**Comment by nikivdev** [comment]
Yes, this is exactly what I wanted. Thank you so much for this. ♥
